### ISSUE TITLE
bug/ Fill the heart icon on favorited skills

### ISSUE THREAD

**Issue by silvijasaule** [honestworkdao/honestwork-app#48]
<img width="921" alt="image" src="https://user-images.githubusercontent.com/74830190/226898929-d845b951-bbc6-4922-b275-a18ca3f2b766.png">

When a user adds a skill to favorites, the heart icon on the skill should be filled to indicate that the user has already clicked on it.

**Comment by takez0o** [comment]
Related: If not logged in, go to login url on skill actions
